name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true
        submodules: recursive
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Install Godot
      uses: abarichello/godot-ci@master
      with:
        version: 4.4
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        mkdir -p build/linux
        godot --headless --export-release "Linux/X11" build/linux/${{ github.event.repository.name }}.x86_64
        
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/linux
        if-no-files-found: error
